### ISSUE TITLE
No Push Permissions

### ISSUE THREAD

**Issue by crazytimtimtim** [Stratosphere-Studios/777-300ER#1]
@Spherrrical Even though I am part of the organization I don't have permission to push directly to the repository. Could I have those?

Also please enable Github Discussions

**Comment by crazytimtimtim** [comment]
@Spherrrical make sure you added everybody mentioned, and you forgot github discussion.

**Comment by crazytimtimtim** [comment]
@Spherrrical tbh I'd rather @Matt726-S just transfer the ownership of the old account to us and we can fix it up.

This is kinda a hassle, we have a few issues we need to sort out and this is just making it worse. Plus the old repo shows up higher on google because it has more commits and stuff.

so @Matt726 can you give us the old account or fix it up yourself? If you want to do it yourself here is what you need to do:
```
1. convert the account to an organization, use the stratosphere studios email.
2. change the icon to the new logo
3. add @nathroxer @Spherrrical @zeta976 @noahvan123 and me to the org
4. Give us write access to the 777 repo
5. Enable github discussions on the repo.
```
Thanks!

**Comment by crazytimtimtim** [comment]
I'd honestly much rather do that.

**Comment by Spherrrical** [comment]
I can fix it...

**Comment by Spherrrical** [comment]
Done

**Comment by crazytimtimtim** [comment]
> I can fix it...

How can you copy the commit history from the other repo to this one?

The other one shows up higher on google because it has more commits. That's one reason I'd rather use the other one. And it'll be a nightmare to get @Nathroxer to switch. Plus now I have to update a bunch of links but I am lazy.
