### ISSUE TITLE
FMC unlock code

### ISSUE THREAD

**Issue by BRUHegg** [Stratosphere-Studios/777-300ER#100]
### Bug Description
The FMC unlock prompt shows up every time the addon is loaded.

### Version
 - OS: Windows
 - X-Plane Version: 12.05
 - The date you downloaded the plane: Jul 24.2023

### To Reproduce
Load the addon once, enter the unlock code, shut the sim down, load the addon again.

**Comment by crazytimtimtim** [comment]
can't reproduce, try reinstalling the aircraft and trying again
