### ISSUE TITLE
Main gear steers in the opposite direction

### ISSUE THREAD

**Issue by zeta976** [Stratosphere-Studios/777-300ER#11]
@crazytimtimtim Main gear is steering in the opposite direction of the front gear

**Comment by crazytimtimtim** [comment]
I think it already does... Try enabling thee "show all parts in xplane" option in planemaker (expert > visible parts or something) and check in the sim.

**Comment by zeta976** [comment]
I mean, it shouldn't steer in the opposite direction afaik @crazytimtimtim

**Comment by crazytimtimtim** [comment]
Yes, it should. It steers in the opposite direction to reduce the turning radius.

If it turned the same direction the plane would kinda be taxiing sideways, if you understand what I mean.
