### ISSUE TITLE
FMC Unlock Code Page not showing

### ISSUE THREAD

**Issue by geekyaussie2083** [Stratosphere-Studios/777-300ER#119]
## Bug Report
FMC Unlock Code Page not showing
### Bug Description
I had the same problem occurring a few months back. My issue is that the page which you enter your code in on the FMC in order to unlock the other panels is not showing when I load up the page. I just have the menu page. Is there a specific page I need to go to in order to unlock the systems or is the page supposed to show up by default (which means it would be a bug).

### Version
 - OS: Windows
 - X-Plane Version: 12.07
 - The date you downloaded the plane: 9.11.2023

### To Reproduce
Please describe how to reproduce this bug.
Load the Stratosphere 777 X-Plane 12 version.
Click OK to the disclaimer to load up the FMC itself.

### Visual Reference
If applicable, add screenshots or videos to help explain your problem. Your log.txt and a screenshot of the black console window are very helpful for fixing bugs.

### **IMPORTANT: DO THESE STEPS BEFORE YOU POST YOUR ISSUE:**
1. Read the readme and make sure it isn't a known issue.
2. Check the issue has not already been reported
3. Try restarting your sim
4. Try reinstalling the latest version of the 777
5. Send a report either here or in the dev support channel on Discord if none of the above work.
**Make sure you have read the readme instructions BEFORE you post this issue. If you still have the issue, please ensure you have filled out all entries above with CLEAR, CONCISE answers. If so, you may delete this section and post your issue. Deleting this message shows that you have read the readme!**

**Comment by geekyaussie2083** [comment]
No.

**Comment by geekyaussie2083** [comment]
I can see some of the displays behind the instructions display, i.e. the eicas. Should I maybe delete those png files or do I still need to activate the displays through the FMC?

**Comment by remenkemi** [comment]
uh... I'd just try reinstalling the 777 and checking the X-Plane 12 -> Output -> preferences folder and deleting any 777 related files in there.

**Comment by geekyaussie2083** [comment]
You’re a legend. Although the “page” for activation was instead displaying as the menu page, I simply was able to enter the code in the bottom left corner (which it didn’t do before) and all the systems activated. I really appreciate your help.

**Comment by remenkemi** [comment]
No problem, glad you figured it out.

We wanted to get people to actually read the readme so we thought to try "locking" the aircraft until the user finds the code instructions in the readme (and hopefully finds answers to any other questions they may have while looking for it ;) )
All it does is put an image over the displays and doesn't let you do anything on the FMC (and if you were to delete said texture, x-plane has a sort of missing texture thing that will go in its place).

Anyway, once again, glad you got it working!
