### ISSUE TITLE
The sound has bug ? 

### ISSUE THREAD

**Issue by Jerry3379** [Stratosphere-Studios/777-300ER#129]
![0FE4E2FB-E964-4608-97AE-A93A96990FB7](https://github.com/Stratosphere-Studios/777-300ER/assets/161133032/5ebf4fb4-7cbc-4cbf-802e-d155d9a19a5d)
### Bug Description
The sound bug Will let me quit.

### Version
 - OS: [ Windows11]
 - X-Plane Version: [12.0.9-rc5]
 - The date you downloaded the plane: [2024 2/24]

### Visual Reference
If applicable, add screenshots or videos to help explain your problem. Your log.txt and a screenshot of the black console window are very helpful for fixing bugs.

### **IMPORTANT: DO THESE STEPS BEFORE YOU POST YOUR ISSUE:**
1. Read the readme and make sure it isn't a known issue.
2. Check the issue has not already been reported
3. Try restarting your sim
4. Try reinstalling the latest version of the 777
5. Send a report either here or in the dev support channel on Discord if none of the above work.
**Make sure you have read the readme instructions BEFORE you post this issue. If you still have the issue, please ensure you have filled out all entries above with CLEAR, CONCISE answers. If so, you may delete this section and post your issue. Deleting this message shows that you have read the readme!**

**Comment by remenkemi** [comment]
Just click the blue button (should say something along the lines of "understood") and the aircraft will still work
