### ISSUE TITLE
Readme issues?

### ISSUE THREAD

**Issue by starxdddd** [Stratosphere-Studios/777-300ER#138]
### Bug Description
It seems to show a warning and the plane just looks broken

### Version
 - windows 11
 - Xplane 12 (latest version)
 - between june 10-23 2024

### To Reproduce
just keep reusing the plane

### Visual Reference

![image](https://github.com/Stratosphere-Studios/777-300ER/assets/173624122/567c0342-ba8f-4a73-8dce-3fef0787b93a)

**Comment by Ker1010** [comment]
that's just the notify for the unlock code not the warning broken, you can find the code in
...\X-Plane 12\Output\777 Readme Code.txt
