### ISSUE TITLE
Nose disappears before doors close

### ISSUE THREAD

**Issue by remenkemi** [Stratosphere-Studios/777-300ER#145]
The animation does not exist for the nose gear. (This is a blender problem not a code problem.)

The reason it still disappears when gear is up is because I kill gear objects when retracted to possibly improve fps. However, the animation still is not working, so it just disappears once it's supposed to be up.

**Comment by remenkemi** [comment]
Animation has been fixed but still disappears before doors close. Will close issue once I fix that.

**Comment by nathroxer** [comment]
nose gear is fixed!
