### ISSUE TITLE
ISFD wrong dimensions

### ISSUE THREAD

**Issue by nathroxer** [Stratosphere-Studios/777-300ER#155]
Fix the dimensions of the attitude indicator on the ISFD
ex: line thickness, modify colors slightly

![12140268145_0640e05c1d_o](https://github.com/user-attachments/assets/b5f91cdb-24c9-4bbb-ab94-85e4583886ef)
![1](https://github.com/user-attachments/assets/5aea4215-a035-4d00-9617-10a5d1bf2601)

**Comment by remenkemi** [comment]
I'll fix the colors soon and I'll try fixing the thickness too.
If I don't end up fixing the thickness I'll close this once I fix the colors and include this in a new "display texture standardization" issue
