### ISSUE TITLE
Split some things

### ISSUE THREAD

**Issue by BRUHegg** [Stratosphere-Studios/777-300ER#34]
Assign slats and flaps, outboard and inboard ailerons, landing gear and gear doors to different datarefs
This will allow for a more realistic simulation. :)

**Comment by zeta976** [comment]
Could you specify what would be the new datarefs? We should also make sure that all the changes in the visual mofel have an impact in the flight model.

**Comment by zeta976** [comment]
All the datarefs you mentioned are writable and have an impact on the flight model, so I don't get the point of using custom datarefs.

**Comment by zeta976** [comment]
Or do you mean the animations use the wrong default dataerefs? Which might be the case.

**Comment by BRUHegg** [comment]
So here are the datarefs:
sim/flightmodel2/wing/aileron1_deg[0] - left outboard aileron
sim/flightmodel2/wing/aileron1_deg[1] - left inboard aileron
same is for the other side just the dataref has to be sim/flightmodel2/wing/aileron2_deg.
sim/flightmodel2/wing/flap1_deg[0] - flaps
sim/flightmodel2/wing/flap1_deg[1] - slats
nathroxer already knows the what the gear doors have to be set to but gonna leave it here as well just in case
Strato/777/gear/doors[] indexation is the same as for the landing gear: starting from the nose and finishing by the right mlg
Animations use correct datarefs. I just forgot to specify the datarefs. Sorry.

**Comment by crazytimtimtim** [comment]
@nathroxer Have you completed these yet?
