### ISSUE TITLE
Turbine fans missing

### ISSUE THREAD

**Issue by MikeCongo** [Stratosphere-Studios/777-300ER#44]
### Bug Description
Describe your bug here.

This is a very good aircraft, but there is one issue I have noticed. The engine does not appear to have turbines, and you can see through most of it. I apologise if these are features still in development.

![Screenshot 2022-12-04 074314](https://user-images.githubusercontent.com/79345351/205465109-9dc2c9fe-1d6a-4176-bf50-d8d9569c0795.jpg)

### Version
 - OS: Windows
 - X-Plane Version: 11.50
 - The date you downloaded the plane: December 3rd, 2022

### To Reproduce
Please describe how to reproduce this bug.

Flying the aircraft should reproduce the bug, as it is present when ether I fly it

**Comment by crazytimtimtim** [comment]
The X-Plane 11 version is pretty buggy. We are considering removing it around new year's, and by then the XP12 full release will be out. If you want to try the aircraft as it should be, you can use the XP12 demo. By the time it is properly flyable XP12 would have been out for some time and I imagine most people would have switched by then, so it's not really necessary to keep the XP11 version.
