### ISSUE TITLE
Incorrect Gear Door Dataref

### ISSUE THREAD

**Issue by remenkemi** [Stratosphere-Studios/777-300ER#58]
Landing gear doors don't use the correct dataref, `Strato/777/gear/doors`

**Comment by BRUHegg** [comment]
Can you please describe your issue in more detail? I want to know in which condition they malfunction, as I haven't been able to find anything wrong with the way they operate.

**Comment by crazytimtimtim** [comment]
While watching both the dataref and the doors on my end, they arent synchronized. I'll post a video later.

**Comment by remenkemi** [comment]
duplicate of #90
