### ISSUE TITLE
Brakes not working with rudder pedals

### ISSUE THREAD

**Issue by remenkemi** [Stratosphere-Studios/777-300ER#61]
The pitch trim A and B commands don't work with the custom flight controls (probable solution is to just call the main command while both A and B are being called). Toe brake axes don't actuate brakes.

**Comment by crazytimtimtim** [comment]
### --Trim--
Works as expected.

### --Brake behavior observed visually--
Pressing the *left* pedal alone causes the aircraft to veer left. Pressing *both* together seems to actuate both brakes. Pressing the *right* pedal alone does nothing.

### -- `Strato/777/gear/brake_load[0]`--
Unaffected by pedals.

### -- `Strato/777/gear/brake_load[1]`--
Ranges from 0 to 1 when using the *left* pedal only. When using right *AND* left pedals together, it goes up to 2 and starts acting up. The *right* pedal alone does nothing. 

### --`Strato/777/gear/qty_brake_L`--
Unaffected by pedals.

### --`Strato/777/gear/qty_brake_R`--
Affected by the *right* pedal only although I think there are some bugs if the pedal is held too long.

**Comment by crazytimtimtim** [comment]
@BRUHegg i've updated my last comment with the brake pressure datarefs

**Comment by remenkemi** [comment]
Ok I looked into it a bit, it seems that `Strato/777/gear/manual_braking_L` and `Strato/777/gear/manual_braking_R` reflect my pedal inputs correctly. So it appears the left braking works normally, but the right braking only works when the left braking is _also_ being applied.
