### ISSUE TITLE
FMS Issues

### ISSUE THREAD

**Issue by crazytimtimtim** [Stratosphere-Studios/777-300ER#69]
- [ ] Text doesn't fit screen
- [x] IDENT page is missing "NAV DATA" field
- [x] IDENT page "ACTIVE" field seems to be in an incorrect format
- [x] Sort out MENU, FIX, and INIT REF button commands
- [x] Need references to edit EICASCTL page for 777
- [x] Disable screen blanking

**Comment by BRUHegg** [comment]
Don't forget to remove "blinking" of the fmc when changing pages. Here are the refs you needed:
![ref1](https://user-images.githubusercontent.com/109680454/209692045-4fe11b14-080c-4364-aa29-42f905cf1159.png)
![ref2](https://user-images.githubusercontent.com/109680454/209692058-d4390600-b374-434f-aaf5-b478f06921d0.png)
![ref3](https://user-images.githubusercontent.com/109680454/209692070-04e869cc-c252-421b-a6cc-46ff4a58ea89.png)
![ref4](https://user-images.githubusercontent.com/109680454/209692088-259c8583-1bf5-4ac0-81e6-4f3452f24d67.png)
![ref5](https://user-images.githubusercontent.com/109680454/209692100-108c2e3d-cbd3-4754-9692-06a45d4d966e.png)
![ref6](https://user-images.githubusercontent.com/109680454/209692111-54c8ddce-da09-4a36-95c9-c6447d352996.png)
![ref7](https://user-images.githubusercontent.com/109680454/209692121-ccb2ea31-b7c1-484b-adf0-d68ceaefb700.png)

**Comment by BRUHegg** [comment]
Umm, are you sure you've done everything? The text still doesn't fit the screen, so I think, I'll reopen the issue.

**Comment by crazytimtimtim** [comment]
> Umm, are you sure you've done everything? The text still doesn't fit the screen, so I think, I'll reopen the issue.

It's in #73
