### ISSUE TITLE
Unlock the flight instruments

### ISSUE THREAD

**Issue by Sp4ce-M0nkey** [Stratosphere-Studios/777-300ER#75]
### Bug Description
Impossible to validate my code find in \X-Plane 12\Output\777 Readme Code.txt

### Version
 - OS: Windows 10
 - X-Plane Version: 12
 - The date you downloaded the plane: 29/01/2023

### To Reproduce
Re install zip from git

### Visual Reference
![Screen](https://cdn.discordapp.com/attachments/987021982262525952/1069287583739297852/Screenshot_25.png)

**Comment by crazytimtimtim** [comment]
Fixed this from my phone - please let me know if it works as it's hard to check from here.

**Comment by Sp4ce-M0nkey** [comment]
@crazytimtimtim it's fine Thanks
