### ISSUE TITLE
Broken Landing Gear

### ISSUE THREAD

**Issue by crazytimtimtim** [Stratosphere-Studios/777-300ER#8]
@zeta976 The landing gear is broken. Only one of them is visible, and the animations does not animate straight up but is slightly off.

Also, @nathroxer why are there like 3 different landing gear objects?

**Comment by zeta976** [comment]
Yes, only one is animated. Also ,wdym the animation doesn't animate straight up?

**Comment by zeta976** [comment]
Ohh retraction animation is kindda off. I'll fix it.
