### ISSUE TITLE
Freighter mode window frame issues

### ISSUE THREAD

**Issue by remenkemi** [Stratosphere-Studios/777-300ER#89]
![image](https://github.com/Stratosphere-Studios/777-300ER/assets/64425497/59d428a8-d6e3-41cd-8616-d5b18449e5ca)

The bug at the top left happens in both passenger and freighter modes and is a flipped normal.

The window frame issue only happens in freighter mode.

**Comment by crazytimtimtim** [comment]
Flipped normal in the top left has been fixed.
